name: Build Preview Environment

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Preview Environment
        run: |
          az deployment group create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --template-file ./src/ReadingTime6.Web/azure.json --parameters webAppName=${{ secrets.AZURE_WEB_APP_NAME }} environment=preview

      - name: Comment Preview URL on PR
        uses: unsplash/comment-on-pr@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Preview environment ready at https://${{ secrets.AZURE_WEB_APP_NAME }}.azurewebsites.net"
