name: Build Preview Environment


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Preview Environment
        run: |
          az deployment group create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --template-file ./src/ReadingTime6.Web/azure.json --parameters webAppName=${{ secrets.AZURE_WEB_APP_NAME }} environment=preview
